INSERT INTO STAZA(IDS, NAZIVS, BROJKRUG, DUZKRUG, DRZS) VALUES (1, 'Interlagos', 54, 5.91, 4);
INSERT INTO STAZA(IDS, NAZIVS, BROJKRUG, DUZKRUG, DRZS) VALUES (2, 'Silverstone', 56, 6.4, 5);
INSERT INTO STAZA(IDS, NAZIVS, BROJKRUG, DUZKRUG, DRZS) VALUES (3, 'Monza', 60, 5.99, 6);
INSERT INTO STAZA(IDS, NAZIVS, BROJKRUG, DUZKRUG, DRZS) VALUES (4, 'Paul Ricard', 65, 5.51, 7);
INSERT INTO STAZA(IDS, NAZIVS, BROJKRUG, DUZKRUG, DRZS) VALUES (5, 'Hockenheimring', 52, 6.22, 3);