CREATE TABLE DRZAVA (
  IDD INTEGER NOT NULL,
  NAZIVD VARCHAR2(128) NOT NULL,
  CONSTRAINT PK_DRZAVA PRIMARY KEY (IDD)
);

CREATE TABLE VOZAC (
  IDV INTEGER NOT NULL,
  IMEV VARCHAR2(128) NOT NULL,
  PREZV VARCHAR2(128) NOT NULL,
  GODRODJ INTEGER NOT NULL,
  BROJTIT INTEGER,
  DRZV INTEGER,
  CONSTRAINT PK_VOZAC PRIMARY KEY (IDV),
  CONSTRAINT FK_VOZAC_DRZAVA FOREIGN KEY (DRZV) REFERENCES DRZAVA (IDD)
);

CREATE TABLE STAZA (
  IDS INTEGER NOT NULL,
  NAZIVS VARCHAR2(128) NOT NULL,
  BROJKRUG INTEGER NOT NULL,
  DUZKRUG DECIMAL(5,2),
  DRZS INTEGER,
  CONSTRAINT PK_STAZA PRIMARY KEY (IDS),
  CONSTRAINT FK_STAZA_DRZAVA FOREIGN KEY (DRZS) REFERENCES DRZAVA (IDD)
);

CREATE TABLE REZULTAT (
  VOZACR INTEGER NOT NULL,
  STAZAR INTEGER NOT NULL,
  SEZONA INTEGER NOT NULL,
  PLASMAN INTEGER,
  BODOVI INTEGER,
  MAKSBRZINA DECIMAL(5,2) NOT NULL,
  ZAVRSIO CHAR(1) NOT NULL,
  CONSTRAINT PK_REZULTAT PRIMARY KEY (VOZACR, STAZAR, SEZONA),
  CONSTRAINT FK_REZULTAT_VOZAC FOREIGN KEY (VOZACR) REFERENCES VOZAC (IDV),
  CONSTRAINT FK_REZULTAT_STAZA FOREIGN KEY (STAZAR) REFERENCES STAZA (IDS),
  CONSTRAINT CH_SEZONA CHECK (SEZONA > 1949 AND SEZONA < 2020 ),
  CONSTRAINT CH_ZAVRSIO CHECK (ZAVRSIO = 'Y' OR ZAVRSIO = 'N' )
);